vm "default-display" {
	firmware uefi
	display
	boot "/bsd"
	disable
}

vm "explicit-display" {
	firmware uefi
	display {
		resolution 1920x1080
		socket "/tmp/explicit-display.vnc"
	}
	boot "/bsd"
	disable
}
